### ISSUE TITLE
No such file or directory: './raw_data/laptop14_train.xml'

### ISSUE THREAD

**Issue by LonieLee** [lixin4ever/E2E-TBSA#10]
您好，我想请问一下在运行process_data这个文件的时候，FileNotFoundError: [Errno 2] No such file or directory: './raw_data/laptop14_train.xml'出现了这样的错误，
代码部分是这样的
def extract_text(dataset_name):
    """
    extract textual information from the xml file
    :param dataset_name: dataset name
    """
    delset = string.punctuation
    fpath = './raw_data/%s.xml' % dataset_name
    print("Process %s..." % fpath)
数据集不都是txt格式的吗'./raw_data/%s.xml'是不是应该将路径改为data下的txt格式文件

**Comment by lixin4ever** [comment]
semeval的原始数据是xml格式
data下的已经是处理过后的txt文件  不需要再运行process_data.py

**Comment by LonieLee** [comment]
好的，谢谢您
