### ISSUE TITLE
关于输出的问题想请教一下

### ISSUE THREAD

**Issue by DRuiii** [lixin4ever/E2E-TBSA#12]
我运行了程序
作为输出的txt文档里有四列结果 ote_tag, ote_tag_gold, ts_tag, ts_tag_gold
能否请您简要介绍一下这些输出，以及应该选择哪个作为最终结果
谢谢！

**Comment by lixin4ever** [comment]
ts_tag作为最终输出的结果，带有gold后缀的表示ground truth

**Comment by DRuiii** [comment]
好的 谢谢！

**Comment by DRuiii** [comment]
还有一个问题想请教您
程序运行时所使用的数据集是已经处理好的数据集，所有的aspect都已经用T标签标注了，而且已经是T-POS T-NEU这类带有情感极性的标签，想问下关于这里数据集的处理或者所使用的数据集的来源。

**Comment by lixin4ever** [comment]
1. 原始xml数据文件在我们的另一个[仓库](https://github.com/lixin4ever/HAST/tree/master/raw_data)下
2. 预处理可以参考 [process_data.py](https://github.com/lixin4ever/E2E-TBSA/blob/master/process_data.py)，有的边界case没有考虑，不过已经在[issue 8](https://github.com/lixin4ever/E2E-TBSA/issues/8)里面fix了
3. 数据集的描述在SemEval-ABSA challenge的官方网站上就有

**Comment by DRuiii** [comment]
好的 感谢！
