### ISSUE TITLE
Prediction values

### ISSUE THREAD

**Issue by yassmine-lam** [lixin4ever/E2E-TBSA#17]
Hi,

Thank u for sharing ur code with us. However, could u plz tell me what does OTE and TS mean in the running results?

Exceed: test performance: ote: f1: 0.6512, ts: precision: 0.6156, recall: 0.4958, micro-f1: 0.5492

Does OTE mean the results of the aspect target extraction, and TS means the results of the aspect sentiment classification?
So in the example above, the model got an F1-score of 65.12% for OTE task and F1-score of 54.92% for aspect sentiment classification?

Thanks in advance

**Comment by lixin4ever** [comment]
Sorry for incomplete documentation.

Your understanding is correct, OTE and TS here respectively refer to "opinion target extraction" (also known as "aspect term extraction" or "aspect target extraction") and "targeted sentiment analysis" (equivalent to "aspect sentiment classification"). The numbers following them are the evaluation results.

**Comment by yassmine-lam** [comment]
Thank u for ur detailed answer.
