### ISSUE TITLE
I cannot find these datasets ; please give me some info about it 

### ISSUE THREAD

**Issue by uyplayer** [lixin4ever/E2E-TBSA#6]
'yelp_rest1': '/projdata9/info_fil/lixin/Research/yelp/yelp_vec_200_2_win5_sent.txt',
'yelp_rest2': '/projdata9/info_fil/lixin/Research/yelp/yelp_vec_200_2_new.txt', 'amazon_laptop':'/projdata9/info_fil/lixin/Resources/amazon_full/vectors/amazon_laptop_vec_200_5.txt'

**Comment by lixin4ever** [comment]
Just ignore these three files and change the ``emb_name`` to "glove_*"
