### ISSUE TITLE
why the word like xxxAspectxxx in sentence?

### ISSUE THREAD

**Issue by BigHeartC** [lixin4ever/E2E-TBSA#8]
Hi, lixin, thanks for your great work. I have a doubt about the dataset, For example, In laptop14_test.text:

> In fact I still use manyLegacy programs (Appleworks, FileMaker Pro, Quicken, Photoshop etc)!####In=O fact=O I=O still=O use=O manyASPECT0=O Appleworks=T-NEU ,=O FileMaker=T-NEU Pro=T-NEU ,=O Quicken=T-NEU ,=O Photoshop=T-NEU etc=O !=O

In laptop14_train.text:
> With the macbook pro it comes with freesecuritysoftware to protect it from viruses and other intrusive things from downloads and internet surfing or emails.####With=O the=O macbook=O pro=O it=O comes=O with=O freeASPECT0=O to=O protect=O it=O from=O viruses=O and=O other=O intrusive=O things=O from=O downloads=O and=O internet=O surfing=O or=O emails=O .=O

> The Apple applications (ex.iPhoto) are fun, easy, and really cool to use (unlike the competition)!####The=O Apple=T-POS applications=T-POS exASPECT1=O are=O fun=O ,=O easy=O ,=O and=O really=O cool=O to=O use=O unlike=O the=O competition=O !=O .=O

Why 'manyLegacy', 'freeASPECT0' and 'ex.iPhoto' become 'manyASPECT0, 'freeASPECT0' and 'exASPECT1'？ This happens many times in Laptop and Restaurant datasets

**Comment by lixin4ever** [comment]
Thank you for pointing our this. 

Here, ASPECT0 (or ASPECT1) refers to the id of aspect term within the sentence. Since aspect term can be phrase (i.e., multiple consecutive words), we replace the spans of aspect terms in the sentence (see the "from" and "to" attributes in the original xml [data files](https://github.com/lixin4ever/HAST/tree/master/raw_data)) with their aspect ids before tokenization. After the tokenization, we retrieve the aspect term (as well as aspect sentiment) according to the aspect id and recover the textual input.  

However, as you can see, some aspect spans in the original files are not isolated but directly follow other words. This will cause tokenization errors and thus the corresponding aspect term can not be recovered. 

I check the processed data files and there are indeed some errors (< 5) in the SemEval testing datasets. Fortunately, all of the experiments are conducted on the same datasets and I think the comparison with the baseline models is still fair.

**Comment by lixin4ever** [comment]
The code below is the function used (and refined) in my current project. You can adapt this piece of code into your pre-processing script. 
```python
def parse(xml_text, tokenizer):
    """
    parse the xml to the structured input
    :param xml_text: text content of the xml file
    :return:
    """

    polarity2tag = {'positive': 'POS', 'negative': 'NEG', 'neutral': 'NEU'}
    selector = Selector(text=xml_text)
    sent_nodes = selector.xpath("//reviews/review/sentences/sentence")
    sent_lines = []
    for sent in sent_nodes:
        text = sent.xpath(".//text/text()").get()
        if text is None or text == '':
            continue
        text = process_string(text)
        opinions = sent.xpath(".//opinions/opinion")
        data_record = []
        visited = []
        visited_f, visited_t = [], []
        #print("Original text:", text)
        for opinion in opinions:
            # aspect term or opinion target
            target = opinion.xpath('@target').get()
            # restore the escape character
            target = process_string(target)
            _from = int(opinion.xpath('@from').get())
            _to = int(opinion.xpath('@to').get())
            polarity = opinion.xpath('@polarity').get()
            if polarity == 'conflict' or target == 'NULL':
                # ignore the conflict case and the case with NULL target
                continue
            if (_from, _to) in visited:
                continue
            if _from in visited_f:
                continue
            if _to in visited_t:
                continue
            # aspect category
            category = opinion.xpath('@category').get()
            #print("text[_from:_to]:", text[_from:_to])
            #print("target:", target)
            assert target.lower() == text[_from:_to].lower()
            # use text[_from:_to] rather than target to gurantee the case-insensitivity
            data_record.append((text[_from:_to], _from, _to, polarity, category))
            visited.append((_from, _to))
            visited_f.append(_from)
            visited_t.append(_to)
        # sort the records according to the start position
        sorted_data_record = sorted(data_record, key=lambda tuple: tuple[1])
        target2annotations = {}
        offset = 0
        for idx, (target, _from, _to, polarity, category) in enumerate(sorted_data_record):
            # place holder for aspect/target string
            target_place_holder = "ASPECT-%s" % idx
            target2annotations[target_place_holder] = (target, _from, _to, polarity, category)
            # shift the index
            _from += offset
            _to += offset
            #print("text[_from:_to]:", text[_from:_to])
            #print("target:", target)
            assert text[_from:_to] == target
            text = text[:_from] + target_place_holder + text[_to:]
            offset += (len(target_place_holder) - len(target))
        raw_tokens = tokenizer.tokenize(text)
        tokens = [process_token(t) for t in raw_tokens]
        #print("Post text:", text)
        word_lines = []
        for t in tokens:
            if 'ASPECT-' not in t:
                term_tag = 'O'
                category_tag = 'NIL'
                term = t
                word_lines.append('%s\t%s\t%s\n' % (term, term_tag, category_tag))
            else:
                target, _from, _to, polarity, category = target2annotations[t]
                # target can be a multi-word phrase
                #terms = list(word_tokenize(target))
                terms = [process_token(t) for t in tokenizer.tokenize(target)]
                for term in terms:
                    term_tag = 'T-%s' % polarity2tag[polarity]
                    category_tag = category
                    word_lines.append('%s\t%s\t%s\n' % (term, term_tag, category_tag))
        word_lines.append('\n')
        sent_lines.append(''.join(word_lines))
    return sent_lines
```

**Comment by BigHeartC** [comment]
I got it, thanks for your patient answer!
